services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
#     networks:
#       - iscte-eventos-network

# networks:
#   iscte-eventos-network:
#     external: true

# volumes:
#   db_data: